### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#665]
## Optimization of data acquisition
- [ ] Step 1: Replace triggers with redux actions #667
- [ ] Step 2: Get rid of multiple dispatch invocations #663
- [ ] Step 3: Create 'hydrate' api methods for each important page #664

## Optimization of data flow
- [x] Step 1: Implement custom selectors for each page (redux container) #661
- [x] Step 2: Refactor all components to use Immutable #662

Each one of the optimizations will benefit both the client and server.
