### ISSUE TITLE
Implement user's bookmarks

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#741]
Drafts show us user defined bookmarks at the bottom of left sidebar's menu: https://github.com/Lokiedu/libertysoil-site/wiki/Left-menu.

We need to add support to manipulate bookmarks at both API and client levels. In roadmap:

- [x] add url's validation tools to figure out if it's correct, if it belongs to some LibertySoil's routes and if there's actual page with such address at LibertySoil.
- [x] add tools to create a bookmark with exact order in user's bookmarks list
- [ ] ... to create a bookmark with default order (insert to the beginning of list or to the end) - _**done for insertion to the end**_
- [ ] ... to create a bookmark with specified icon
- [x] add support of fetch the metadata of pages with URL (to create readable bookmark but enter only its address)
- [ ] add tools to update bookmarks' URL, title, icon and order - _**done for URL, title and order**_
- [x] allow users to delete bookmarks
- [ ] (probably) create new page representing the list of all bookmarks which centain user has

Related pull request: https://github.com/Lokiedu/libertysoil-site/pull/712

**Comment by xekc** [comment]
@Oopscurity I need you to do a review of your progress here. Things are rapidly changing and I need to understand well what's available here, how it works, could it be left out. I need screenshots and your explanation of what doesn't work yet - please get ready, refresh it in your head and let's discuss #741 in Slack.

**Comment by xekc** [comment]
I'll re-open this as an epic as long as we need to continue with this work and release the feature set in our next release.

**Comment by xekc** [comment]
This issue was moved to Lokiedu/LS-Specification#87
