### ISSUE TITLE
Left menu improvements

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#923]
## Current:
![2017-9w5i0](https://user-images.githubusercontent.com/1575753/32014516-31bdb21e-b9b6-11e7-869b-875c3acb7b55.png)

![image](https://user-images.githubusercontent.com/1575753/32014902-54bd1452-b9b7-11e7-9b4c-a49e2c7a04dc.png)

## Expected:
![image](https://user-images.githubusercontent.com/1575753/32014559-4718773e-b9b6-11e7-844b-5719d3420eaa.png)

### Responsive:
![image](https://user-images.githubusercontent.com/1575753/32014619-781d54bc-b9b6-11e7-95f5-25fe81fae296.png)

### SVG icons and colour coding:
![image](https://user-images.githubusercontent.com/1575753/32014641-8e3ee526-b9b6-11e7-99da-b9469801c46b.png)

### Custom emoji-run menu item symbols
![image](https://user-images.githubusercontent.com/1575753/32014691-b53c5c9e-b9b6-11e7-96f4-d5d9c04de9d8.png)

## Enhancements for logged out / anon user
- [x] Adjust font family / sizes
- [ ] Adjust text labels and provide additional elements
  - [x] Change "All" to "All Posts"
  - [ ] Counter indicates the number of posts posted in the last 24 hours
  - [x] Icons are larger (all of them)
- [x] Remove "Feed" - what does it do? 
- [x] Add "Most Liked", "Most Favourited", "All Time Best" client side code / visual side @Oopscurity 

- [x] Develop a feed with "Most Liked" posts for the last 30 days, by number of Likes. @voidxnull 
- [x] Develop a feed with "Most Favourited" posts for the last 30 days, by number of adds to Favs. @voidxnull 
- [x] Develop a feed with "All Time Best" posts that have achieved a maximum number for Comments+Favorites+Likes+(ability to extend criteria/kpi list easily) metrics. @voidxnull 

- [x] Develop a full analogue for "Location tags", "Hashtags", "Schools" menu block that is in registered logged in user's menu:

![image](https://user-images.githubusercontent.com/1575753/32015538-48920956-b9b9-11e7-8150-efdb0e2bf62d.png)

  - [x] Block contains most recently used (post contains) tags in each category (Locations, Hashtags, Schools).
  - [ ] https://alpha.libertysoil.org/feed/tag https://alpha.libertysoil.org/feed/geo https://alpha.libertysoil.org/feed/s - working for anon visitors.
  - [ ] No-js / search-engines focused page version?

- [ ] Oversee integration, do code review, merge and launch on Alpha @indeyets 
- [ ] Performance analysis request: how growth of information / number of users, posts will affect our performance needs. What expectations can we make? How do we speed posts delivery in each request and have a lot of custom filters too?

## Enhancement for registered logged in user

![image](https://user-images.githubusercontent.com/1575753/32014921-6923d110-b9b7-11e7-9927-e5e07b4ddd25.png)
![image](https://user-images.githubusercontent.com/1575753/32014929-6e336e36-b9b7-11e7-9947-d9ad41dfd5d3.png)

- [x] The hover needs tuning. "Mouse over" state is too far from the regular state. Please remove background color change on mouse over. Only text color will change.
- [x] Icons opacity (Globe, Heart, Star) should not change and remain the same: 

![image](https://user-images.githubusercontent.com/1575753/32015061-dbf271d8-b9b7-11e7-96fc-8f56e80af7f4.png)

- [x] Currently active filter (All Posts for example) - is not clickable. 

- [x] Change "All" to "All Posts"
- [x] Change "Feed" to "My Friends"
- [x] Change "Likes" to "Liked"
- [x] Change "Favourites" to "Most Favourited"

- [x] Add "Most Liked" 
- [x] Add "Most Favourited"
- [x] Add "All Time Best"

## Tags, Schools, Locations

![2017-9w5i0](https://user-images.githubusercontent.com/1575753/32015466-1925e28c-b9b9-11e7-8ce7-57021a072062.png)

- [x] For anon users display counter number for the last 24h
- [ ] For registered signed in user counter of unread posts in tags I follow

## Review

- [ ] Review responsive behaviour, live chat Q&A @Oopscurity + material above ("Responsive" section).

**Comment by xekc** [comment]
@voidxnull тут в центре текста описания этой задачи есть твои задачи, ты бы мог посмотреть, всё ли там понятно? Нужно сделать фиды доступные для юзера - доступными для публики тоже (с небольшой модификацией логики).
