### ISSUE TITLE
Top Navigation improvements

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#925]
## Current
For a logged out user switcher looks like this:
![2017-8pmpe](https://user-images.githubusercontent.com/1575753/32020319-b2752660-b9c7-11e7-85fb-8466fc50737a.png)

Logo area:
![image](https://user-images.githubusercontent.com/1575753/32021332-03a0eca6-b9cb-11e7-9503-37cafd5c84d6.png)

![2017-77hqy](https://user-images.githubusercontent.com/1575753/32021366-1f9a1b6c-b9cb-11e7-89c0-2ee8e3302507.png)

## Improvements

- [ ] We need to move languages switcher to the footer. All available languages need to be listed as hyperlinks. We'll move to add a number of language versions soon. 

- [x] Text "Login" shouldn't be visible. We need to put 60x60 square with with a "Login" icon: 

![image](https://user-images.githubusercontent.com/1575753/32020927-b3bf767c-b9c9-11e7-8e25-5e42ad870155.png)

- [x] On top of image: 

![image](https://user-images.githubusercontent.com/1575753/32020951-c7081964-b9c9-11e7-85a0-62d16a166393.png)

- [x] In top menu:

![image](https://user-images.githubusercontent.com/1575753/32021081-3b195d0e-b9ca-11e7-94d7-39f0fd53491c.png)

## Left side 

- [x] Logo with tags: 
![image](https://user-images.githubusercontent.com/1575753/32021694-fc67d228-b9cb-11e7-8cc7-0e8306d09c38.png)

- [x] Logo with text:

![image](https://user-images.githubusercontent.com/1575753/32021715-0ff403d4-b9cc-11e7-901c-d0f45b60e0b5.png)

## Overall view

- [x] Desktop:

![2017-2d3fi](https://user-images.githubusercontent.com/1575753/32021747-34d9b68a-b9cc-11e7-97c0-342826c9059d.png)

- [x] Mobile:

![image](https://user-images.githubusercontent.com/1575753/32022033-1f3b27cc-b9cd-11e7-96a8-155c31d681cc.png)

- [x] Mobile for logged in user:

![image](https://user-images.githubusercontent.com/1575753/32022412-3ce2a434-b9ce-11e7-8191-431a0478d8a6.png)

**Drop-down current:**

![image](https://user-images.githubusercontent.com/1575753/32022456-5b453982-b9ce-11e7-8b96-98cb5aa28df3.png)

- [x] Drop-down improvements:

![image](https://user-images.githubusercontent.com/1575753/32022553-af64e7f6-b9ce-11e7-9cd2-56b74a234977.png)

- [x] Make sure the distance between the top navigation bar and the content is 20px.

- [x] Top of the left menu and of the first post has to be on the exactly same level:
![2017-cnpgp](https://user-images.githubusercontent.com/1575753/32023401-12a812fa-b9d1-11e7-8999-410298f273c5.png)

**Comment by xekc** [comment]
➤ Vladimiras Lekecinskas commented:

@oopscurity есть какие-нибудь непонятные моменты в карточке? ты можешь над этим работать? я хочу наиболее грубые моменты поправить asap.

**Comment by artkravchenko** [comment]
@xekc,
1. Прозрачность отдельных элементов.
  - Overall view: для авторизованного пользователя кнопка поиска полупрозрачна, для анонима - непрозрачна. Все верно?
  - Цветовые различия (разные оттенки полупрозрачных элементов) означают реакцию на наведение/клик? Или постоянны? Есть логика выстраивания оттенков в ряду?
2. При наведении мыши (или клике) на элементы шапки есть визуальные эффекты? Тот же вопрос относительно элементов выпадающего списка.
3. Как ведет себя активное поле поиска? Изменяется цвет фона и перекрываются хлебные крошки или название страницы, подобно реализации в альфе? Выпадающий список с результатами поиска пока остается прежним?
4. Меню выбора языка.
> We need to move languages switcher to the footer.

Поскольку мы практикуем потенциально бесконечные ленты содержимого с автоматической загрузкой, не станет ли меню недосягаемым?
> All available languages need to be listed as hyperlinks.

Имеется в виду изменение адреса страницы? В данный момент переключение никак на адрес не влияет.

5. Расстояние между шапкой и основным содержимым страницы.
> Make sure the distance between the top navigation bar and the content is 20px.

Это не касается контейнера с меню, присутствующего на небольших разрешениях экрана?

Внешний вид сообщений под шапкой ("Welcome to...") остается прежним?

**Comment by xekc** [comment]
1.1 Нет, "непрозрачная" это ховер. Аноним или нет видят кнопку поиска одинаково.

1.2 Цветовые различия могут быть моими багами вполне, нужно прорабатывать каждый такой баг отдельно. ховер обычно это переход opacity от 80%-90% к 100% для текста / символа - без изменения фона. Это для того, чтобы на тачскрин устройствах был более близкий к десктопу ответ интерфейса.

2-3 я добавлю в следующую итерации работы над этими элементами, пока тут ничего не делаем.

4.1 В футере будет список ссылок на языки. То, что футер сейчас невозможно увидеть - это недоработка, но это отдельно от этой задачи. Подгрузку в ленту нужно переделать.

4.2 Нет, переключение интерфейса на другой язык ничего не должно делать с адресом страницы. Только если у нас будет фильтрация контента по языкам сделана (именно контента, а не интерфейсов сайта), тогда это будет отражаться в адресе. 

5.1 Это меню недоработано и не должно так себя вести тоже, но да, от него тоже 20пх, сейчас гуляет. 

5.2 Welcome to будет сделан полностью иначе, этот можно отключать, он уродливый и это не может работать удобно для юзеров.

Любые дополнения out of scope и мы пока делаем только то, что в таске описано, в следующий раз доделаем поиск и другие детали.
